import struct
import os

# SERVER CONSTS

SERVER_VERION =  2

# INET C STRUCTS

CONNECTION_FORMAT = "@H46s" # port, address
INET_HEADER_FORMAT = CONNECTION_FORMAT + "II" #  CONNECTION, message_size, message_type

DB_OR_FORMAT = "24sI" # OBJECT, RECORD

CONNECTION_SIZE = struct.calcsize(CONNECTION_FORMAT)
INET_HEADER_SIZE = struct.calcsize(INET_HEADER_FORMAT)

# INET ENVIRONMENT VARIABLES

KDB_INET_ADDRESS_ENV = "KDB_INET_ADDRESS"
KDB_INET_ADDRESS = os.getenv(KDB_INET_ADDRESS_ENV)